INSERT INTO prodotto(prezzo, quantità, descrizione, foto, nome)VALUES(2, 200, 'carina', 'https://www.diamondcentre.it/24819/penna-a-sfera-montblanc-montblanc-2.jpg', 'Penna');
INSERT INTO prodotto(prezzo, quantità, descrizione, foto, nome)VALUES(7, 300, ' la tazza in ceramica è personalizzata con il logo del Museo Egizio.', 'https://shop.museoegizio.it/media/catalog/product/cache/7a8ec44ad576ba30cfc5b61d0c386784/t/a/tazza_me.jpg', 'Tazze');
INSERT INTO prodotto(prezzo, quantità, descrizione, foto, nome)VALUES(20, 400, 'Libri che ripercorrono le varie epoche', 'https://miramare.cultura.gov.it/wp-content/uploads/2023/12/WhatsApp-Image-2023-12-23-at-14.53.38-3-1080x675.jpeg', 'Libri');
INSERT INTO prodotto(prezzo, quantità, descrizione, foto, nome)VALUES(10, 150, 'Poster di alta qualità raffiguranti opere d arte famose', 'https://i.etsystatic.com/39700963/r/il/99a133/4864035676/il_794xN.4864035676_gm4o.jpg', 'Poster');
INSERT INTO prodotto(prezzo, quantità, descrizione, foto, nome)VALUES(30, 100, 'Repliche dettagliate di statue famose del museo', 'https://i.etsystatic.com/8459873/r/il/ece210/2776983001/il_fullxfull.2776983001_26nb.jpg', 'Repliche statue');
INSERT INTO prodotto(prezzo, quantità, descrizione, foto, nome)VALUES(25, 200, 'Gioielli ispirati alle opere d arte del museo', 'https://th.bing.com/th/id/OIP.bOKaYrW6dI4RvqqkGwCJLQHaEb?rs=1&pid=ImgDetMain', 'Gioielli');
INSERT INTO prodotto(prezzo, quantità, descrizione, foto, nome)VALUES(15, 300, 'Puzzle e giochi educativi con temi artistici e storici', 'https://ae01.alicdn.com/kf/S89aa0e6e3c954d2c9c79a06dcfa7d5d62/MaxRend-Jigsaw-Puzzle-1000-pezzi-per-adulti-opere-d-arte-fini-Klimt-The-Kiss-carta-ecologica.jpg_640x640.jpg_.webp', 'Puzzle');
INSERT INTO prodotto(prezzo, quantità, descrizione, foto, nome)VALUES(8, 300, 'Set di cartoline con opere d\'arte famose del museo', 'https://www.quickmuseum.it/wp-content/uploads/2018/06/blog-5-opere-louvre-quickmuseum.jpg', 'Cartoline');
INSERT INTO prodotto(prezzo, quantità, descrizione, foto, nome)VALUES(35, 50, 'Modellini dettagliati di edifici o strutture architettoniche del museo', 'https://www.ferrostoria.com/pimages/TEMPIO-EGIZIO-extra-big-762-056.jpg', 'Modellini architettonici');

