INSERT INTO prodotto(prezzo, quantita, descrizione, foto, nome)VALUES(7, 300, ' Le tazze da museo sono prodotti che rappresentano o celebrano opere d arte. Le tazze sono realizzate con materiali di alta qualità come ceramica o porcellana. Immagini sulle tazze sono stampati con cura per garantire una riproduzione fedele dell opera.', '/tazza-museo.png', 'Tazze');
INSERT INTO prodotto(prezzo, quantita, descrizione, foto, nome)VALUES(20, 400, 'Benvenuto nella nostra sezione libri, un tesoro di conoscenza che ti accompagna in un viaggio attraverso le epoche e le culture. Scegli tra una varietà di opere che si fondono armoniosamente con la vastità e la diversità delle nostre collezioni. ', 'https://i.pinimg.com/originals/97/bd/c4/97bdc4bdda3c33e762a96637db28b61c.jpg', 'Libri');
INSERT INTO prodotto(prezzo, quantita, descrizione, foto, nome)VALUES(10, 150, 'I poster si presentano come un’affascinante fusione di arte e informazione. Raffigurano le opere d’arte più famose e importanti.  Con sfondi sfumati che evocano un senso di mistero e scoperta, il design complessivo emana un\'aura di eleganza. ', 'https://i.pinimg.com/originals/5f/60/70/5f607049abb0386f2637fce208ce3342.jpg', 'Poster');
INSERT INTO prodotto(prezzo, quantita, descrizione, foto, nome)VALUES(30, 100, 'Le repliche di statue sono riproduzioni artistiche di opere originali, realizzate per emulare l\'aspetto e i dettagli delle creazioni originali. Queste repliche possono essere realizzate in diversi materiali e possono variare nelle dimensioni.', '/statua-arte.png', 'Repliche statue');
INSERT INTO prodotto(prezzo, quantita, descrizione, foto, nome)VALUES(25, 200, 'Un set completo di gioielli che fondono design contemporaneo con lusso senza tempo. Ogni pezzo è caratterizzato da linee pulite e materiali di alta qualità, creando un insieme armonioso che si adatta ad ogni occasione.', '/gioielli-arte.png', 'Gioielli');
INSERT INTO prodotto(prezzo, quantita, descrizione, foto, nome)VALUES(15, 300, 'Immergiti in un\'avventura unica nel suo genere con il nostro puzzle "Viaggio nel Tempo". Questo puzzle è progettato per portarti attraverso le epoche storiche e ti sfiderà a collegare i pezzi del passato in un affascinante mosaico di conoscenza.', '/puzzle-arte.png', 'Puzzle');
INSERT INTO prodotto(prezzo, quantita, descrizione, foto, nome)VALUES(8, 300, 'Le cartoline del museo sono progettate per catturare l\'essenza delle opere d\'arte esposte. Presentano immagini di opere d\'arte famose, sculture, reperti storici. Le cartoline di un museo contengono informazioni sulla storia delle opere d\'arte.', '/cartoline-arte.png', 'Cartoline');
INSERT INTO prodotto(prezzo, quantita, descrizione, foto, nome)VALUES(35, 50, 'I modelli architettonici esposti in un museo sono parte di mostre che mirano a presentare l\'architettura in tutte le sue sfaccettature. I modelli architettonici sono rappresentazioni tridimensionali di progetti architettonici, realizzate in scala.', '/TEMPIO-EGIZIO-modellino.png', 'Modellini architettonici');
INSERT INTO prodotto(prezzo, quantita, descrizione, foto, nome) VALUES (60, 15, 'Il vaso artistico è un capolavoro che cattura l\'attenzione degli spettatori con la sua eleganza e la sua bellezza intrinseca. Realizzato con una maestria artigianale impeccabile, il vaso si presenta come un\'armoniosa fusione di forme e colori. ', '/vaso-arte.png', 'Vaso Artistico');
INSERT INTO prodotto(prezzo, quantita, descrizione, foto, nome) VALUES (180, 8, 'La tela d\'arte moderna cattura immediatamente l\'attenzione degli spettatori con la fusione di colori, forme e concetti. Il colore è uno degli elementi chiave di questa opera d\'arte moderna', '/tela-moderna.png', 'Tela d\'Arte Moderna');
INSERT INTO `role` (name) VALUES('ADMIN');
INSERT INTO `role` (name) VALUES('USER');
INSERT INTO museum_user (email, first_name, last_name, password) VALUES('admin', 'Jane', 'Doe', '{noop}admin');
INSERT INTO museum_user (email, first_name, last_name, password) VALUES('user', 'John', 'Doe', '{noop}user');
INSERT INTO museum_user_role_set (museum_user_id, role_set_name) VALUES(1, 'ADMIN');
INSERT INTO museum_user_role_set (museum_user_id, role_set_name) VALUES(1, 'USER');
INSERT INTO museum_user_role_set (museum_user_id, role_set_name) VALUES(2, 'USER');

